basic_auth_users:
  prometheus: $2y$12$S/nkKU/NBOBUJrsizWfFwueb4.kEcBBLH6pa3ODRYDu1c2gBXL7DG
tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt 
  key_file: /etc/node_exporter/node_exporter.key